BoardGameArena/Controllers/GameController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using BoardGameArena.Data;
using BoardGameArena.Models;
using BoardGameArena.Repositories;
using BoardGameArena.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace BoardGameArena.Controllers
{
    public class GameController : Controller
    {
        private readonly GameRepository gameRepository;
        private readonly IWebHostEnvironment host;

        public GameController(GameRepository GameRepository, IWebHostEnvironment host)
        {
            this.gameRepository = GameRepository;
            this.host = host;
        }


        public ActionResult Index()
        {
            var listeGames = this.gameRepository.FindAll();
            return View(listeGames);
        }

        [HttpGet("admin/games", Name ="admin_games")]
        [Authorize(Roles ="Admin")]
        public ActionResult AdminIndex()
        {
            if (TempData["success"] != null)
            {
                this.ViewBag.success = TempData["success"];
            }
            var listeGames = this.gameRepository.FindAll();
            return View("AdminIndex",listeGames);
        }

        [HttpGet("admin/game/nouveau",Name ="admin_game_create_get")]
        [Authorize(Roles ="Admin")]
        public ActionResult Create()
        {
            FormGameViewModel model = new FormGameViewModel();
            return View(model);
        }

        [HttpPost("admin/game/nouveau", Name = "admin_game_create_post")]
        [Authorize(Roles = "Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(FormGameViewModel model)
        {
            if (ModelState.IsValid)
            {
                Game Game = new Game()
                {
                    Title = model.Title,
                    Rules = model.Rules,
                    Description = model.Description,
                    NbMin = model.NbMin,
                    NbMax = model.NbMax
                };

                string UniqueTitle = null;
                if(model.CoverImage != null)
                {
                    var PathFolder = Path.Combine(this.host.WebRootPath, "img", "game");
                    UniqueTitle = Guid.NewGuid().ToString() + "_" + model.CoverImage.FileName;
                    var FilePath = Path.Combine(PathFolder, UniqueTitle);
                    if (!Directory.Exists(PathFolder))
                    {
                        Directory.CreateDirectory(PathFolder);
                    }
                    model.CoverImage.CopyTo( new FileStream(FilePath, FileMode.Create));

                    Game.CoverImage = UniqueTitle;
                }

                this.gameRepository.Create(Game);
                this.TempData["success"] = $"Le jeux {Game.Title} a bien été crée été";
                return RedirectToRoute("admin_games");

            }
            return View(model);
        }

        [HttpGet("game/detail/{id:int}", Name ="GameDetail")]
        [HttpGet("admin/game/detail/{id:int}", Name ="AdminGameDetail")]
        public IActionResult Detail(int Id)
        {
            Game Game = this.gameRepository.FindOneById(Id);
            return View(Game);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet("admin/game/edit/{id:int}", Name ="AdminGameEdit")]
        public IActionResult Edit(int Id)
        {
            Game Game = this.gameRepository.FindOneById(Id);
            if(Game != null)
            {
                FormGameViewModel model = new FormGameViewModel()
                {
                    Id = Game.Id,
                    Title = Game.Title,
                    NbMax = Game.NbMax,
                    NbMin = Game.NbMin,
                    Description = Game.Description,
                    Rules = Game.Rules
                };

                this.ViewBag.Game = Game;
                return View(model);

            }

            return BadRequest();
        }

        [Authorize(Roles ="Admin")]
        [HttpPost("admin/game/update/", Name = "AdminUpdateGame")]
        public IActionResult Update(FormGameViewModel model)
        {
            if (ModelState.IsValid)
            {
                Game Game = this.gameRepository.FindOneById(model.Id);
                if (Game != null)
                {

                    string UniqueCoverImage = Guid.NewGuid().ToString() + "_" + model.CoverImage.FileName;
                    var folderPath = Path.Combine(this.host.WebRootPath, "img", "game");
                    var PathFile = Path.Combine(folderPath, UniqueCoverImage);
                    if (!Directory.Exists(folderPath))
                    {
                        Directory.CreateDirectory(folderPath);
                    }
                    model.CoverImage.CopyTo(new FileStream(PathFile, FileMode.Create));
                    Game.Title = model.Title;
                    Game.NbMin = model.NbMin;
                    Game.NbMax = model.NbMax;
                    Game.Rules = model.Rules;
                    Game.Description = model.Description;
                    Game.CoverImage = UniqueCoverImage;
                    this.gameRepository.Update(Game);
                }
                return RedirectToAction("Detail", new { Id = model.Id });

            }
            return View(model);
        }

        [HttpGet("admin/game/delete/{id:int}", Name ="admin_game_delete")]
        [Authorize(Roles ="Admin")]
        public IActionResult Delete(int id)
        {
            Game Game = this.gameRepository.FindOneById(id);
            Game = this.gameRepository.Delete(Game);
            this.TempData["success"] = $"Le jeu {Game.Title} bien été supprimé";
            return RedirectToRoute("admin_games"); 
        }

    }
}

BoardGameArena/Controllers/PartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BoardGameArena.Data;
using BoardGameArena.Models;
using BoardGameArena.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace BoardGameArena.Controllers
{
    public class PartController : Controller
    {
        private readonly UserManager<Player> userManager;
        private readonly GameRepository gameRepository;
        private readonly PlayerRepository playerRepository;
        private readonly PartRepository partRepository;

        public PartController(UserManager<Player> UserManager,GameRepository GameRepo, PlayerRepository PlayerRepo, PartRepository PartRepo)
        {
            userManager = UserManager;
            this.gameRepository = GameRepo;
            this.playerRepository = PlayerRepo;
            this.partRepository = PartRepo;
        }


        public IActionResult Index()
        {
            IEnumerable<Part> ListParts = this.partRepository.FindAll();
            return this.View(ListParts);
        }


        [HttpGet("/nouvelle/partie" ,Name = "new-part")]
        [Authorize]
        public IActionResult Create()
        {
            ViewBag.Games = this.gameRepository.FindAll();
            ViewBag.Players = this.playerRepository.FindAll();

            return View();
        }

        [HttpPost("/nouvelle/partie", Name = "new-part-post")]
        [Authorize]
        public IActionResult Create(string title, int id_game, int[] id_players)
        {
            this.partRepository.Create(title, id_game, id_players);

            return RedirectToAction("Index", "Home");
        }


        [HttpGet("partie/detail/{id:alphanumeric}")]
        public IActionResult Detail(int Id)
        {
            ViewBag.error = null;
            if (TempData["ErrorMessage"] != null)
            {
                ViewBag.error = TempData["ErrorMessage"];
            }
            Part Part = this.partRepository.findOneById(Id);
            return View(Part);
        }

        [HttpGet("partie/edit/{id:int}",Name ="getPartEdit")]
        [HttpGet("admin/partie/edit/{id:int}", Name = "getPartEditAdmin")]
        [Authorize]
        public IActionResult Edit(int Id)
        {
            Part Part = this.partRepository.findOneById(Id);
            if(Part.IsFinish && !this.User.IsInRole("Admin"))
            {
                TempData["ErrorMessage"] = "La partie est Terminée, Impossible de la modifier";
                return RedirectToAction("Detail", new { Id = Id });

            }
            else
            {
                return View(Part);
            }
        }

        [HttpPost("partie/edit/{id:int}", Name = "postPartEdit")]
        [HttpPost("admin/partie/edit/{id:int}", Name = "postPartEditAdmin")]
        public IActionResult Edit(int PartId, int[] score)
        {
            Part Part = this.partRepository.findOneById(PartId);
            if ((Part.IsFinish && this.User.IsInRole("Admin")) || !Part.IsFinish)
            {
                var Form = HttpContext.Request.Form;
                if (Part != null)
                {
                    this.partRepository.Update(Part, Form);
                }
                return RedirectToAction("Detail", new { Id = PartId });
            }
            return BadRequest();
        }
    }
}

BoardGameArena/Controllers/PlayerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BoardGameArena.Data;
using BoardGameArena.Models;
using BoardGameArena.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace BoardGameArena.Controllers
{
    public class PlayerController : Controller
    {
        private readonly PlayerRepository playerRepository;
        private readonly UserManager<Player> userManager;

        public PlayerController(PlayerRepository PlayerRepo, UserManager<Player> userManager)
        {
            this.playerRepository = PlayerRepo;
            this.userManager = userManager;
            
        }

        public IActionResult Index()
        {
            IEnumerable<Player> ListePlayers = this.playerRepository.FindAll();
            return View(ListePlayers);
        }

        public IActionResult Detail(int Id)
        {
            Player Player = this.playerRepository.FindOneByid(Id);
            return View(Player);
        }


        //-----------------------ADMIN ------------------------------

        [HttpGet("admin/players", Name ="admin_players")]
        [Authorize(Roles ="Admin")]
        public IActionResult IndexAdmin()
        {
            if (TempData["success"] != null)
            {
                this.ViewBag.success = TempData["success"];
            }
            if (TempData["error"] != null)
            {
                this.ViewBag.error = TempData["error"];
            }

            IEnumerable<Player> Players = this.playerRepository.FindAll();
            return View(Players);
        }

        [HttpDelete("admin/player/delete/{id:int}", Name ="admin_player_delete")]
        [Authorize(Roles ="Admin")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int Id)
        {
            var user = await this.userManager.FindByIdAsync(Id.ToString());
            if(user != null)
            {
                if(user.PartPlayers.Count() == 0)
                {
                    var result = await this.userManager.DeleteAsync(user);
                    if (result.Succeeded)
                    {
                        this.TempData["success"] = $"Le Joueur {user.UserName} a bien été supprimé";

                    }
                    else
                    {
                        TempData["error"] = "L'utilisateur n'a pas pu être supprimé";
                    }

                }
                else
                {
                    TempData["error"] = "L'utilisateur n'a pas pu être supprimé car il a joué une ou plusieurs partie";
                }
                
            }
            else
            {
                TempData["error"] = "L'utilisateur n'a pas été trouvé";
            }

            return RedirectToRoute("admin_players");
        }
    }
}

BoardGameArena/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BoardGameArena</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        
        <nav class="navbar navbar-expand-md navbar-toggleable-sm navbar-dark bg-dark box-shadow">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BoardGameArena</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Part" asp-action="Index">Les Parties</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Game" asp-action="Index">Les Jeux</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Player" asp-action="Index">Nos Joueurs</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">

                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link " asp-area="" asp-controller="Admin" asp-action="Index">Admin</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Account" asp-action="MyAccount">Mon Compte</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Account" asp-action="Logout">Deconnection</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Account" asp-action="Register">S'inscrire</a>
                        </li>

                    }
                </ul>
            </div>
        </nav>
    </header>
    <div class="error container-fluid">
        @if(!string.IsNullOrEmpty(ViewBag.error))
        {
            <div class="alert alert-danger" role="alert">
                @ViewBag.error
            </div>
            
        }
    </div>
    <div>
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BoardGameArena - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/ckeditor/ckeditor.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

BoardGameArena/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BoardGameArena</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-toggleable-sm navbar-light bg-white box-shadow mb-3">
            <a class="navbar-brand" asp-area="" asp-controller="Admin" asp-action="Index">BoardGameArena Admin</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Admin" asp-action="ListRole">Les Roles</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-route="admin_players">Nos Joueurs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Game" asp-action="AdminIndex">Nos Jeux</a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Account" asp-action="MyAccount">Mon Compte</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " asp-area="" asp-controller="Account" asp-action="Logout">Deconnection</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="success container-fluid">
        @if (!string.IsNullOrEmpty(ViewBag.success))
        {
            <div class="alert alert-success" role="alert">
                @ViewBag.success
            </div>

        }
    </div>
    <div class="error container-fluid">
        @if (!string.IsNullOrEmpty(ViewBag.error))
        {
            <div class="alert alert-danger" role="alert">
                @ViewBag.error
            </div>

        }
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BoardGameArena - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/ckeditor/ckeditor.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>